---
title: "Sample Article"
author: "by mathslug"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r echo=FALSE}
library(ggplot2)
library(knitr)
```


## A New Paradigm

R comes with a built in dataset called `iris` about flowers or something. This is groundbreaking news. We should make a re-usable header strip to go at the top of all these articles.

## Iris Data Graph

``` {r fig.width=6, fig.height=6, fig.align='center', echo=FALSE}
ggplot(iris) + geom_line(aes(x=Sepal.Length, y=Petal.Length)) + theme(plot.title = element_text(size = 20), 
    panel.background = element_rect(fill = "lawngreen", 
        colour = "antiquewhite3"), plot.background = element_rect(fill = "aliceblue", 
        size = 0.6, linetype = "solid")) +labs(title = "Oh No!", subtitle = "What are we to do", 
    caption = "Data from built-in R dataset")
```

## A Closer Look

As we can see, the data speaks for itself.

```{r, echo=FALSE, results='asis'}
kable(head(iris, 10))
```

## Stay Tuned

Dont. Stop. Watching.
